### ISSUE TITLE
Extra backslash("\") in the readme.md file present in Create Identity section 

### ISSUE THREAD

**Issue by suryakanthrai** [canonical/kratos-operator#23]
### Bug Description

In the readme.md file there is a backslash("\"). I am attaching the image of it for more information 
![image](https://user-images.githubusercontent.com/46310284/208813717-d3f88a10-f411-4aac-ad14-1b784f51d606.png)

### To Reproduce

Go to the readme.md file in the Create Identity section there is a backslash at the end of first three statements.

### Environment

I am able to see in the windows environment.

### Relevant log output

```shell
NA
```

**Comment by natalian98** [comment]
Hello,
thank you for your input and reaching out to our team.

This charm is currently in development state. Please follow Canonical [blog announcements](https://canonical.com/blog) to keep track of the latest releases.

Best regards,
Identity Team
